### ISSUE TITLE
documenting data

### ISSUE THREAD

**Issue by lecy** [Nonprofit-Open-Data-Collective/compensator#1]
It's good practice to add all package datasets to a file called "data.r". 

There are a couple of ways to document the data.

https://r-pkgs.org/data.html

In another context you need a docType of data and the return value for datasets is NULL: 

https://github.com/Nonprofit-Open-Data-Collective/titleclassifier/blob/main/R/data.R

I am not sure if having R scripts in the data folder will cause errors when you try to compile the package. If so, you can move the raw files and the data scripts to a data-raw folder. 

It's a good practice to add a README and describe the raw files.

**Comment by olbeck** [comment]
- I moved the data set documentation to data.R, and moved the making-*-data.R files to the data-raw/ folder. 

- For the documentation in data.R, should I follow the documentation format of the link for `titleclassifier` package or the format from the R Package book? I was following the format in section 8.2.1 and 8.2.2 of the R Packages book and the structure from the `babynames` package (https://github.com/hadley/babynames/blob/master/R/data.R). I can change it to the format in `titleclassifer` package if you would prefer.   

- Should I move the table in `R/EIN_filtering.rda` into `R/sysdata.rda`? (following the advice of section 8.3 of the R Packages book) The EIN_filtering table is just data from the `R/nonprofits.rda` table, but in a more convenient format for filtering. The nonprofits table would be for the user to see and the EIN_filtering table is only for inside the `R/dat-filtering.R` function. The user technically never needs to see the EIN_filtering table to see their comparison set.

**Comment by lecy** [comment]
> should I follow the documentation format of the link for titleclassifier package or the format from the R Package book?

I see what you were doing - when there are multiple approaches I defer to the R Studio group (Wickam, Bryan, Xie), so the current style works. 

I am curious about why they don't use a docType tag so the package knows it is a dataset. 

```
#' @docType data
```

And why the book lists the dataset name in quotes after the Roxygen comments whereas previous versions use NULL. We should clarify whether this is a **usethis** convention vs an **Rtools** convention (the original package used to create packages). Specifically, if you follow one convention do you need to use the correct package to generate the documentation? Or are these Roxygen conventions that have changed? 

> Should I move the table in R/EIN_filtering.rda into R/sysdata.rda?

That makes sense if it is only internal use. Would we want the dataset available to demo functionality? In the documentation of functions, or more likely in a vignette that explains the operationalization of matching in the package? If so, I would make it public. If not, it can stay private.

**Comment by olbeck** [comment]
doctype resolved
