### ISSUE TITLE
exporting pipes

### ISSUE THREAD

**Issue by lecy** [Nonprofit-Open-Data-Collective/compensator#2]
There are always many ways to do things in R, so your export of the pipe operator might be fine. But this also works: 

```
# make the pipe operator 
# available through the
# magrittr package

#' @importFrom magrittr "%>%"
```

It means it can be called from within functions in the package, but it would not make the operator available for users after loading this package. So internal use scope, I think.

**Comment by olbeck** [comment]
I used the `use_pipe()` function from the `usethis`package. 
https://usethis.r-lib.org/reference/use_pipe.html 

I can add the way you mentioned if you'd prefer. Or I can switch `export = F` to be only an internal function.

**Comment by lecy** [comment]
Got it. That works.
