### ISSUE TITLE
add argument defaults

### ISSUE THREAD

**Issue by lecy** [Nonprofit-Open-Data-Collective/compensator#4]
It might be helpful to have reasonable argument defaults for this step: 

```
dat_filtering <- function(BroadCategroy = NA, 
                          MajorGroup = NA, 
                          Decile = NA, 
                          CommonCode = NA, 
                          University = NA,
                          Hostipal = NA, 
                          Location = NA, 
                          State = NA, 
                          TotalExpenses = c(0, Inf)){
 
```

Defaults can help users see what the appropriate input types are for arguments, and can make them easier to use without listing a long string of arguments. I would only set defaults if they are unlikely to cause problems, though. For example, universities and hospitals are probably FALSE. We might include a state vector as a dataset and by default use all states? 

Try to avoid capitalization in argument names unless it's useful. 

Hospital is spelled wrong in the argument list. 

If the data is loaded properly by the package you can reference the dataset name directly instead of through the load() function. 

```
  #load data 
  load("data/EIN_filtering.rda")  # don't need this
  
  dat.filtered <- EIN_filtering
```

**Comment by olbeck** [comment]
Issues fixed: 
- added defaults that won't cause error. Defaulted to all regular organizations 
- removed capitalization 
- fixed hospital 
- loaded data properly.
