### ISSUE TITLE
NTEE Codes 

### ISSUE THREAD

**Issue by olbeck** [Nonprofit-Open-Data-Collective/compensator#6]
For the `ntee.crosswalk` table, I was looking through to see the unique NTEE codes. There are some that do not make any sense. For example, I ran `table(ntee.crosswalk)` and this is some of the output: 

<img width="709" alt="Screen Shot 2023-01-07 at 1 30 34 PM" src="https://user-images.githubusercontent.com/55454718/211165415-f395769a-a4cf-4e76-9386-80c95902c900.png">

There is "A6A", "A6B", "A6C", and "A6E". I do not know what these ones mean. 

"A6A" appears to all be orgs about opera
<img width="312" alt="Screen Shot 2023-01-18 at 5 41 18 PM" src="https://user-images.githubusercontent.com/55454718/213311156-ca275848-4e72-4e37-8d68-193ce52489fe.png">

"A6B" appears to be mostly children's choirs 
<img width="362" alt="Screen Shot 2023-01-18 at 5 42 33 PM" src="https://user-images.githubusercontent.com/55454718/213311300-524da822-d598-4b78-b675-5cf5df8424ff.png">

"A6C" are small music ensembles 
<img width="393" alt="Screen Shot 2023-01-18 at 5 43 22 PM" src="https://user-images.githubusercontent.com/55454718/213311381-cd5163c4-5c96-40e3-b6b6-4a1a01a83f28.png">

"A6E" appear to be music schools/workshops 
 
<img width="460" alt="Screen Shot 2023-01-18 at 5 44 41 PM" src="https://user-images.githubusercontent.com/55454718/213311644-ae95a0af-92de-4a00-9b5e-5333766d2da3.png">

**Comment by olbeck** [comment]
In addition, the code "A267" appears. However the orgs that have this code are mostly *StateName* Humanities Council.


<img width="395" alt="Screen Shot 2023-01-18 at 5 40 02 PM" src="https://user-images.githubusercontent.com/55454718/213310912-4a6bdc4f-2775-40ce-82fe-1211f5cc806a.png">

What should we do with these ones?

**Comment by lecy** [comment]
A6A-A6D are actually defined categories: 

https://github.com/Nonprofit-Open-Data-Collective/machine_learning_mission_codes/raw/master/docs/assets/NTEE_Two_Page_2005.pdf

* A6A Opera
* A6B Singing & Choral Groups
* A6C Bands & Ensembles
* A6E Performing Arts Schools

It looks like A267 is possibly a weird combination of A26 and A27? Or maybe more likely just A26?  

* A26 Arts & Humanities Councils & Agencies
* A27 Community Celebrations 

Would the others - B0121 - follow the standard you identified before? B01 + B21? 

B = Education 
B01 Alliances & Advocacy 
B21 Preschools

**Comment by olbeck** [comment]
> A6A-A6D are actually defined categories:
> 
> https://github.com/Nonprofit-Open-Data-Collective/machine_learning_mission_codes/raw/master/docs/assets/NTEE_Two_Page_2005.pdf
> 
> * A6A Opera
> * A6B Singing & Choral Groups
> * A6C Bands & Ensembles
> * A6E Performing Arts Schools
> 


These ones are added to the ntee.crosswalk. For the "ones" place for these organizations, should we leave it as the letter A, B, C, or E. Or should be just make the ones place 0? 

Since the "tens" place is already 6, they are already being classified with the other organization with Major Group A and tens place 6.

**Comment by olbeck** [comment]
> Would the others - B0121 - follow the standard you identified before? B01 + B21?
> 
> B = Education B01 Alliances & Advocacy B21 Preschools


That is correct. 
<img width="825" alt="Screen Shot 2023-02-02 at 3 16 20 PM" src="https://user-images.githubusercontent.com/55454718/216440073-411a7a64-dcd6-4983-9bed-70295ee2055d.png">

**Comment by olbeck** [comment]
Codes with letter in the subdivision location have been left in the `ntee.crosswalk` data set, but were removed from the dendrogram because they were causing errors.
